### ISSUE TITLE
Make estimate delivery date visible

### ISSUE THREAD

**Issue by norkator** [norkator/paketin-seuranta#123]
Bug

**Comment by ristomatti** [comment]
Where does this info come? This is Schenker related?

This is likely unrelated but I'd like if the info on how many days has passed since the order date/creation date (with the same start day logic for the info you see after the order is completed). Currently I check this from parcelsapp.com as it has this:

![image](https://user-images.githubusercontent.com/9029939/115137228-8927ee00-a02d-11eb-8325-dff0e39da4fe.png)

Technically it's not the same thing as I think it doesn't allow entering the time of purchase but anyway.

I can create this as a separate issue if you wish.
