### ISSUE TITLE
Matkahuolto delivery icon/state wrong after reminder message

### ISSUE THREAD

**Issue by ristomatti** [norkator/paketin-seuranta#152]
I've got a package waiting for pickup. It already had ready for pickup icon but it changed back to have the "in transport" icon. 

Phase value is "IN_TRANSPORT" for both states, only the status description differs. Currently it is:

> Lähetimme vastaanottajalle muistutuksen lähetyksen saapumisesta (tekstiviesti).

Earlier status texts:

> Lähetimme vastaanottajalle muistutuksen lähetyksen saapumisesta (sähköposti).

> Lähetimme vastaanottajalle viestin lähetyksen saapumisesta (tekstiviesti).

> Lähetys on noudettavissa pakettipisteestä Pakettiautomaatti R-kioski ××××××× 28.7.2021 asti

**Comment by norkator** [comment]
This is probably because https://github.com/norkator/paketin-seuranta/blob/master/app/src/main/java/com/nitramite/courier/MatkahuoltoStrategy.java defaults to `PHASE_IN_TRANSPORT` and https://github.com/norkator/paketin-seuranta/blob/master/app/src/main/java/com/nitramite/paketinseuranta/PhaseNumber.java fails with:

> Lähetimme vastaanottajalle muistutuksen lähetyksen saapumisesta (tekstiviesti).

**Comment by norkator** [comment]
I need to re-check this implementation to see if theres new ways to determine that phase since those text based checks are hacky.
