### ISSUE TITLE
All packages with phase WAITING show customs icon

### ISSUE THREAD

**Issue by ristomatti** [norkator/paketin-seuranta#57]
Special icon for packages waiting for customs declaration was my feature request but it's appeared the logic to show it on WAITING phase doesn't seem to be adequate. WAITING phase seems to be used also for packages waiting for pickup from the sender.

Maybe this could be fixed with an additional check for the delivery status? Unfortunately I don't have any such package right now to get the status text but I have one bigger package from China coming and it likely will get stuck in customs. I can update the issue if/when that happens.

**Comment by ristomatti** [comment]
Update: the package got stuck in customs as expected. But it made this even more complicated. The package now shows:
- "in transport" icon instead of customs icon
- package details show it can already be picked up even though the latest status "Lähetys on rekisteröity" with the phase `IN_TRANSPORT`.

I'm out of ideas how to best solve this. This the first time the customs icon does not appear so this might be some special snowflake case.

**Comment by norkator** [comment]
> Update: the package got stuck in customs as expected. But it made this even more complicated. The package now shows:
> 
> * "in transport" icon instead of customs icon
> * package details show it can already be picked up even though the latest status "Lähetys on rekisteröity" with the phase `IN_TRANSPORT`.
> 
> I'm out of ideas how to best solve this. This the first time the customs icon does not appear so this might be some special snowflake case. Any ideas @norkator?

Send me your tracking code IF possible at Trello, I want to see my own eyes what is going on.

**Comment by norkator** [comment]
Okay my notes about this case are:

![image](https://user-images.githubusercontent.com/55850510/91659876-42f03f80-eadb-11ea-9645-c892bef6f9a4.png)
This is shown because API is providing this information already and we don't have handling with this banner + current phase, do we want that?

![image](https://user-images.githubusercontent.com/55850510/91659896-5c918700-eadb-11ea-93cc-ebf9c184e9cb.png)
As said parcel is in customs with state IN_TRANSPORT

![image](https://user-images.githubusercontent.com/55850510/91659903-674c1c00-eadb-11ea-9198-d996ba2c6f01.png)
We use only newest status to determine does it need customs handling but:

![image](https://user-images.githubusercontent.com/55850510/91659916-792dbf00-eadb-11ea-823e-aa9dd4fc52c1.png)
now there is never status saying this.. I am out of ideas. Parsing every event line to determine customs handling is too dangerous.

**Comment by ristomatti** [comment]
This seems like a mess. I agree it sounds too hacky to go through all the statutes for the customs status. It might be simpler to just put the feature behind a disabled feature flag for now until we get more examples?

**Comment by norkator** [comment]
Closing for now. Open back if we see something happening to this.
